"""
Data schemas for synthetic clinical notes pipeline.

Defines pandas dtype schemas for the main datasets: encounters, admissions,
patients, and clinical notes. Adapted from nhsengland/synthetic_clinical_notes.
"""

encounter_schema = {
    "administrative_category_code": "string",
    "administrative_category_code_on_admission": "string",
    "administrative_category_description": "string",
    "admission_method": "string",
    "admission_status": "string",
    "admission_sub_status": "string",
    "admission_type": "string",
    "ats_total_theatre_time": 'Int32',
    "calculated_total_theatre_time": 'Int32',
    "created_by": "string",
    "created_date": object,
    "criteria_to_reside": "string",
    "critical_care_bed_status": "string",
    "disease_outbreak_notification_description": "string",
    "disease_outbreak_notification_snomed_ct": "string",
    "division": "string",
    "eal_id": "string",
    "encounter_free_text": "string",
    "encounter_id": "string",
    "encounter_type": "string",
    "estimated_total_theatre_time": 'Int32',
    "external_id": "string",
    "has_future_tci": "boolean",
    "has_tci": "boolean",
    "hospital_provider_spell_identifier": "string",
    "intended_management_code": "string",
    "intended_management_description": "string",
    "intended_primary_procedure_anaesthetic_type": "string",
    "intended_primary_procedure_anaesthetist_required": "boolean",
    "intended_primary_procedure_code": "string",
    "intended_primary_procedure_description": "string",
    "intended_primary_procedure_free_text": "string",
    "intended_primary_procedure_free_text_long": "string",
    "is_booked": "boolean",
    "is_metric_encounter": "boolean",
    "is_suitable_for_pooled_list": "boolean",
    "issues": object,
    "last_covid_swab_booking_status": "string",
    "last_covid_swab_outcome": "string",
    "last_mrsa_swab_booking_status": "string",
    "last_mrsa_swab_outcome": "string",
    "last_poa_booking_status": "string",
    "last_poa_expiry_date": object,
    "last_poa_outcome": "string",
    "last_poa_outcome_date": object,
    "last_poa_outcome_free_text": "string",
    "last_poa_scheduled_or_attended_datetime": 'datetime64[ns]',
    "latest_rcs_clinical_harm_review": "string",
    "local_treatment_function": "string",
    "needs_reprioritisation": "boolean",
    "patient_cancellation_count": 'Int32',
    "patient_id": "string",
    "patient_name": "string",
    "pathway_id": "string",
    "peri_op_risk_stratification_outcome": "string",
    "peri_op_risk_stratification_outcome_date": object,
    "poa_required": "string",
    "primary_consultant_id": "string",
    "primary_consultant_name": "string",
    "primary_diagnosis_icd": "string",
    "primary_procedure_opcs": "string",
    "primary_procedure_start_time": 'datetime64[ns]',
    "primary_procedure_type": "string",
    "priority": "string",
    "priority_last_updated": 'datetime64[ns]',
    "priority_ordered": "string",
    "referral_priority": "string",
    "remain_reason": "string",
    "removal_date": object,
    "removal_reason": "string",
    "removal_reason_code": "string",
    "removed": "boolean",
    "secondary_diagnosis_icd": "string",
    "site": "string",
    "site_id": "string",
    "specialty_id": "string",
    "specialty_name": "string",
    "suspected_cancer_pathway": "boolean",
    "tci_date": object,
    "tci_status": "string",
    "title": "string",
    "transfer_status": "string",
    "treatment_function_code": "string",
    "treatment_function_name": "string",
    "waitlist_code": "string",
    "ward": "string",
    "rv_group_ids": object,
    "rv_modules": object
}

admission_schema = {
    "admission_id": "string",
    "admission_method": "string",
    "admission_source_hospital_provider_spell": "string",
    "admission_status": "string",
    "admission_timestamp": 'datetime64[ns]',
    "admission_title": "string",
    "admission_type": "string",
    "bed_location": "string",
    "date_of_birth": "string",
    "destination_of_discharge_hospital_provider_spell": "string",
    "discharge_destination_type": "string",
    "discharge_pathway": "string",
    "discharge_ready_date_hospital_provider_spell": 'datetime64[ns]',
    "discharge_timestamp": 'datetime64[ns]',
    "early_discharge_notification_timestamp": 'datetime64[ns]',
    "encounter_id": "string",
    "estimated_discharge_date": 'datetime64[ns]',
    "intended_management_code": "string",
    "is_discharge_time_confirmed": "boolean",
    "length_of_stay_days": 'Int32',
    "local_authority": "string",
    "master_delay_reason": "string",
    "method_of_admission_hospital_provider_spell": "string",
    "method_of_discharge_hospital_provider_spell": "string",
    "mrn": "string",
    "ncepod_urgency_code": "string",
    "needs_based_assessment_timestamp": 'datetime64[ns]',
    "nhs_number": "string",
    "patient_classification_code": "string",
    "patient_id": "string",
    "patient_name": "string",
    "site_id": "string",
    "site_name": "string",
    "specialty_id": "string",
    "specialty_name": "string",
    "to_take_away_status": "string",
    "to_take_away_status_timestamp": 'datetime64[ns]',
    "waiting_area": "string",
    "ward": "string",
    "ward_intended_clinical_care_intensity": "string",
    "rv_group_ids": object,
    "rv_modules": object,
    "full_name": "string",
    "first_name": "string",
    "surname": "string"
}

patient_schema = {
    "address_line_1": "string",
    "address_line_2": "string",
    "address_city": "string",
    "age": 'Int64',
    "date_of_birth": object,
    "date_of_death": object,
    "deceased": "boolean",
    "first_name": "string",
    "full_name": "string",
    "gender_identity": "string",
    "mrn": "string",
    "next_of_kin_name": "string",
    "next_of_kin_number": "string",
    "nhs_number": "string",
    "person_id": "string",
    "phone_number": "string",
    "postcode": "string",
    "registered_gp": "string",
    "sex": "string",
    "surname": "string",
    "title": "string",
    "rv_group_ids": object,
    "rv_modules": object
}

note_schema = {
    "note_state": "string",
    "successful_decompression": "boolean",
    "content_type": "string",
    "ingest_timestamp": 'datetime64[ns]',
    "clinical_note_id": "string",
    "clean_note_text": "string",
    "markdown_content": "string",
    "raw_blob_content": "string",
    "attachment_dataset_rid": "string",
    "attachment_file_name": "string",
    "creation_timestamp": 'datetime64[ns]',
    "updt_dt_tm": 'datetime64[ns]',
    "note_subject": "string",
    "note_type": "string",
    "admission_id": "string",
    "encounter_id": "string",
    "person_id": "string"
}

schema_dict = {
    'admissions': admission_schema,
    'patients_output': patient_schema,
    'encounters': encounter_schema,
    'clinical_notes': note_schema
}
